[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "migrate -verbose -path /app/migrations -database \"$DATABASE_URL\" up"
startCommand = "./server"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
