[build]
builder = "dockerfile"

[deploy]
releaseCommand = "ls -la /app && which migrate && migrate -version && migrate -path /app/migrations -database $DATABASE_URL up"
startCommand = "./server"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
