[build]
builder = "dockerfile"

[deploy]
releaseCommand = "sh -c 'echo RELEASE_COMMAND_CALLED && exit 1'"
startCommand = "./server"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
